---
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"
# enable building on container-based infrastructure
sudo: false
install:
  # install dependencies
  - CFLAGS="-O0" pip install -e .[native]
  # install test dependencies
  - CFLAGS="-O0" pip install coveralls
  - python setup.py test
script:
  - python setup.py nosetests
after_script:
  - coveralls
deploy:
  provider: pypi
  user: Dieter.Adriaenssens
  on:
    tags: true
  password:
    secure: UGQmcX4npYdLhCJqJDxWLBvUVSZCYnvlqpvcSsDy6KC8ASwfK6lZh5pRmX/Z1dXDxKynsofJEyAJW9GrkUO7/9xx+r19/UzXbvQ1TS93NP47fNkXc3/ceCRH5gM2hGoQZKUJTL/hnX+aDKAb4c/L76kg+psptANu6iJMnC6yVY4=
notifications:
  webhooks:
    # parse Travis CI log and send result to Keen.io, using Builtime Trend Service
    - https://buildtimetrend-dev.herokuapp.com/travis
    - https://buildtimetrend.herokuapp.com/travis
