language: python
python:
  - "2.7"
# enable building on container-based infrastructure
sudo: false
install:
  - CFLAGS="-O0" pip install -e .[native]
  - CFLAGS="-O0" pip install coveralls
script:
  - nosetests --with-coverage --cover-package=buildtimetrend
after_script:
  - coveralls
notifications:
  webhooks:
    # parse Travis CI log and send result to Keen.io, using Builtime Trend Service
    - http://buildtimetrend-dev.herokuapp.com/travis
