language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
env:
  global:
    secure: "dR5giy/zGN6FmS4rlJ+RTSwKrbcMSxP9TJ4uW3eT7SpcAHBLPmW1/46vMAVGlHSqjdW0w+DxRjxrLMmo9g3ZZsqFExiXM19W2sbyAuwiAa2WLDTL3IdEdw/wCJm9W1usrRB/oGQjsBvkTzzXlobLXUTcADhUfBSj6XjMiduSAsA="
before_install:
  # initialise buildtime-trend scripts
  - source ./init.sh
install:
  - timestamp.sh install
  - CFLAGS="-O0" pip install -r requirements.txt
  - CFLAGS="-O0" pip install -r requirements-tests.txt
script:
  - timestamp.sh tests
  - nosetests --with-coverage --cover-package=buildtimetrend
after_success:
  - timestamp.sh coveralls
  - coveralls
after_script:
  # synchronise buildtime-trend result with gh-pages
  - sync-buildtime-trend-with-gh-pages.sh
