language: python
python:
  - "2.7"
install:
  - CFLAGS="-O0" pip install -e .[native]
  - python setup.py test
script:
  - nosetests --with-coverage --cover-package=buildtimetrend
after_script:
  - coveralls
