language: python
python:
  - "2.7"
env:
  global:
    - secure: "dR5giy/zGN6FmS4rlJ+RTSwKrbcMSxP9TJ4uW3eT7SpcAHBLPmW1/46vMAVGlHSqjdW0w+DxRjxrLMmo9g3ZZsqFExiXM19W2sbyAuwiAa2WLDTL3IdEdw/wCJm9W1usrRB/oGQjsBvkTzzXlobLXUTcADhUfBSj6XjMiduSAsA="
    - secure: "Nm5w1CTqlWlX4qtpd+p+4NzoTV0/DMQHz4cNSAqYlufi/Cr9iQNiEk9Bsp/bh5UMe7EHTDztW5iABbzURhlOfHLVf3wkinATVX3ijzjPJcjVDyY4j2XU8oEszr2hqLl0u8VXUbQSJHzov75Ocuw6b0Oa334HLSyrDszqKaE5VEo="
    - secure: "fa1MLxplPA2TDXrYYq5DCGA5PAAxXhz1FDyDwLSzIPayKzeefLod87nSBz7vsFsfqBastw8p6lXzBihRFHGy3o2HCWCOccd5GVDK50BdcccWTOvVHkgW1a99NgsMsRTjUlWnVcDe2PuVuzCRbnvSuA9ruKtcVhJguXihf1sWVw8="
before_install:
  # initialise buildtime-trend scripts
  - source ./init.sh
install:
  - timestamp.sh install
  - CFLAGS="-O0" pip install -r requirements.txt
  - CFLAGS="-O0" pip install -r requirements-tests.txt
script:
  - timestamp.sh tests
  - nosetests --with-coverage --cover-package=buildtimetrend
after_success:
  - timestamp.sh coveralls
  - coveralls
after_script:
  # synchronise buildtime-trend result with gh-pages
  - sync-buildtime-trend-with-gh-pages.sh
