language: python
env:
  global:
    secure: "V5RpOtEm4K4H8hXTPcaPu/z3cbGEdhYyEvN79+qQsGmaymODOFlw53SWPamg7ko6KQXJOu4niZVFU0+IOYxSZqPjXGe5h49+5byp87xhlT/P0vRQdeNC2UDPH4e9O3o+GGB9/yNzyCOOh0G+2M31jK4AkwzXFsMs5wEupuiAOdE="
    secure: "Nm5w1CTqlWlX4qtpd+p+4NzoTV0/DMQHz4cNSAqYlufi/Cr9iQNiEk9Bsp/bh5UMe7EHTDztW5iABbzURhlOfHLVf3wkinATVX3ijzjPJcjVDyY4j2XU8oEszr2hqLl0u8VXUbQSJHzov75Ocuw6b0Oa334HLSyrDszqKaE5VEo="
    secure: "fa1MLxplPA2TDXrYYq5DCGA5PAAxXhz1FDyDwLSzIPayKzeefLod87nSBz7vsFsfqBastw8p6lXzBihRFHGy3o2HCWCOccd5GVDK50BdcccWTOvVHkgW1a99NgsMsRTjUlWnVcDe2PuVuzCRbnvSuA9ruKtcVhJguXihf1sWVw8="
before_install:
  # initialise buildtime-trend scripts
  - source ./init.sh
install:
  - timestamp.sh install
  - CFLAGS="-O0" pip install -r requirements.txt
  - CFLAGS="-O0" pip install -r requirements-tests.txt
script:
  - timestamp.sh tests
  - nosetests --with-coverage --cover-package=buildtimetrend
after_success:
  - timestamp.sh coveralls
  - coveralls
after_script:
  # synchronise buildtime-trend result with gh-pages
  - sync-buildtime-trend-with-gh-pages.sh
