language: python
python:
  - "2.7"
install:
  - CFLAGS="-O0" pip install -r requirements.txt
  - CFLAGS="-O0" pip install -r requirements-native.txt
  - CFLAGS="-O0" pip install -r requirements-tests.txt
script:
  - nosetests --with-coverage --cover-package=buildtimetrend
after_script:
  - coveralls
