language: python
env:
  global:
    secure: "V5RpOtEm4K4H8hXTPcaPu/z3cbGEdhYyEvN79+qQsGmaymODOFlw53SWPamg7ko6KQXJOu4niZVFU0+IOYxSZqPjXGe5h49+5byp87xhlT/P0vRQdeNC2UDPH4e9O3o+GGB9/yNzyCOOh0G+2M31jK4AkwzXFsMs5wEupuiAOdE="
install: CFLAGS="-O0" pip install -r requirements.txt
script: ./test/test_timestamp.sh
after_script:
  # synchronise buildtime-trend result with gh-pages
  - sync-buildtime-trend-with-gh-pages.sh
