# Buildtime Trend general settings
buildtimetrend:
    project_name: "project_name or git repo"
    mode_native: false
    mode_keen: true
    loglevel: "WARNING" # possible values : "DEBUG", "INFO", "WARNING", "ERROR"
    data_detail: "full" # level of detail when storing build job data : "minimal", "basic", "full", "extended"
    dashboard_sample_configfile: "path/to/config_sample.js"
    dashboard_configfile: "path/to/config.js"
    task_queue:
        backend: "" # fe. amqp, redis, ...
        broker_url: "" # format : transport://userid:password@hostname:port/virtual_host
    multi_import:
        max_builds: 100 # maximum number of builds allowed in one batch
        delay: 3 # number of seconds between the start of each build

# Keen.io connection settings
keen:
    project_id: "Keen.io project_id"
    write_key: "Keen.io write_key"
    read_key: "Keen.io read_key"
    master_key: "Keen.io Master API key"
