python_exec: python
pip_exec: pip
python_requirements:
  - '/vagrant/requirements.txt'
  - '/vagrant/requirements_test.txt'
  - '/vagrant/requirements_native.txt'
extra_libraries:
  - libxml2-dev
  - libxslt1-dev
  - zlib1g-dev
  - python-libxml2
  - python-libxslt1
  - libpng12-dev
  - libfreetype6-dev
