- name: "Download Pip installer"
  get_url: url=https://bootstrap.pypa.io/get-pip.py dest=/tmp/get-pip.py
  register: pipinstaller

- name: "Install Python pip"
  command: "{{ python_exec }} /tmp/get-pip.py"
  when: pipinstaller|success
  register: pipinstalled

- name: "Install Python nose"
  apt: name="{{ python_exec }}-nose" state=latest
  register: noseinstalled

- name: "Install required libraries"
  apt: name={{item}} state=latest
  with_items:
    - pkg-config
    - "{{ python_exec }}-dev"
    - libxml2-dev
    - libxslt1-dev
    - zlib1g-dev
    - python-libxml2
    - python-libxslt1
    - libpng12-dev
    - libfreetype6-dev
  register: libsinstalled

- name: "Install python requirements"
  pip:
    requirements={{ item }}
    executable={{ pip_exec }}
  when: pipinstalled|success and libsinstalled|success
  with_items: "{{ python_requirements }}"
